name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - main

jobs:
  e2e:
    name: PPE test
    runs-on: ubuntu-latest
    env:
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      GH_PAT_TOKEN: ${{ secrets.GH_PRIVILEGED_PAT_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v4

      - name: npm install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run E2E Smoke Test
        id: tests
        run: npm run test:e2e

      - name: Run E2E Local Test
        id: local_tests
        run: npm run test:e2e-local
