name: normal

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  fake-job:
    name: fake-job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: PR event number
        run: echo "`${console.log('test1234')}`" > pr_num.txt

      - name: Upload the PR event number
        uses: actions/upload-artifact@v4
        with:
          name: pr_num
          path: ./pr_num.txt
