name: Python CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [released]
  workflow_dispatch:

env:
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: true
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11']
        args: ['-m unit']
        flags: ['unittests']
        include:
          - python: '3.10'
            args: -m integration
            flags: integration
          - python: '3.11'
            args: -m integration
            flags: integration
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: ${{ matrix.tools }}
        uses: microsoft/action-python@0.7.1
        with:
          pytest: true
          args: ${{ matrix.args }}
          workdir: '.'
          testdir: 'tests'
          python_version: ${{ matrix.python }}
          flags: ${{ matrix.flags }}-${{ matrix.python }}