name: "Run TODO to Issue"
on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set Git user
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email `git log -n 1 --pretty=format:%ae remotes/origin/${{ github.head_ref }}`